### ISSUE TITLE
ERROR 403 plz help

### ISSUE THREAD

**Issue by SarahMiri226** [GGR-Devs/GGReborn-App#26]
- [X] I am using the [latest](https://github.com/GGR-DEVS/GGReborn-App/releases/latest) GGRebornApp version
- [X] I have searched the [issues](https://github.com/GGR-DEVS//GGReborn-App//issues) and not found any issue what looks like mine, or similar.
- [ ] I have enabled to store logs, and I want to share it.

- **OS name and version**:  Windows 10
- **App version**: 0.0.7

## Issue

I've downloaded and installed the app all just right, but when i open the "GGRebornApp", it shows a 403 error page:
![error page](https://github.com/user-attachments/assets/b689ccc1-4225-4959-bd29-caebb1416c3e)
I've searched in the files and at the Issues page on Github, but i found nothing
Please helpp

**Comment by BXn4** [comment]
Hey! It's like the website is down. @SulivanM will fix it before the open, early test. As I said in the announcement:
I'll ping again here, when its starting. Just wait, and it will come...

Note: Just for christmas, and the server is still not ready. This is not the beta, I just start the server to everyone, who waited to play.

**Comment by SulivanM** [comment]
Sure, I will soon replace the 403 error page with a message like: "The test is closed. Please wait for the next one."

**Comment by SulivanM** [comment]
Website Back !
